//! M9 #107/#108: frozen BusyBox/rootfs convergence on the production Linux path.
//!
//! Each cycle runs the exact #100 command matrix (generated from
//! `fixtures/busybox/frozen/commands.toml` by `build.rs`) as
//! `/bin/sh -c "export PATH=/bin; <shell>"`, then capability-denial and timeout probes.
//! Every cycle ends with a resource snapshot that must equal the baseline. The host
//! validator (`cargo xtask test-m9-userspace`) re-checks the logged stdout bytes against
//! `commands.toml` together with the sleep, denial and resource evidence.

use crate::arch::x86_64::context_switch::{restore_task_context, task_stack_top};
use crate::arch::x86_64::gdt::set_privilege_stack;
use crate::arch::x86_64::interrupt_context::InterruptContext;
use crate::diagnostics::log::{kernel_log_fmt, kernel_log_line};
use crate::diagnostics::qemu::{fatal_kernel_error, qemu_exit, QEMU_EXIT_SUCCESS};
use crate::interrupt::timer::{initialize_timer, kernel_ticks};
use crate::mm::frame_allocator::PageAllocator;
use crate::mm::paging::current_root_frame_address;
use crate::mm::PAGE_SIZE;
use crate::process::domain::DomainTeardownResult;
use crate::process::id_allocator::{id_allocator_mut, IdAllocator};
use crate::process::linux_exec::{
    launch_linux_process_with_authority, pick_scheduler_slot_for_relaunch, LinuxExecSpec,
    LinuxLaunchAuthority,
};
use crate::process::linux_fd::{
    self, console_sink_render_style, open_description_pool_live_count, ConsoleSinkRenderStyle,
    OpenDescriptionId,
};
use crate::process::linux_fs::object_backend::{bootstrap_tmp_file_bytes, tmp_file_live_count};
use crate::process::linux_image::{
    LINUX_CONVENTIONAL_EXEC_STACK_PAGES, LINUX_CONVENTIONAL_LOAD_POLICY,
};
use crate::process::linux_mem;
use crate::process::linux_proc::{
    pipe::pool,
    table::{proc_table_invariant_violations, table},
};
use crate::process::linux_rootfs;
use crate::process::live_instance_generation;
use crate::process::personality::{execution_personality_for_pid, ExecutionPersonality};
use crate::process::process_registry_mut;
use crate::sched::dispatch::start_current_scheduler_thread;
use crate::sched::wait::{waiter_occupancy_where, WaitOutcome};
use crate::sched::{scheduler_mut, task_stacks_mut, Scheduler, SCHEDULER_THREAD_SLOTS};
use crate::selftest::userspace_process::{
    configure_scheduler_thread_slot, reset_process_scheduler_world,
    spawn_native_userspace_process_with_code,
};
use crate::service::control::ServiceLifecycleController;
use crate::service::service_lifecycle_controller_mut;
use crate::sync::global_cell::GlobalCell;
use crate::syscall::initialize_syscall_abi;
use crate::syscall::{
    install_service_lifecycle_syscall_allocator, service_lifecycle_syscall_allocator_mut,
};
use clean_slate_rootfs::EntryKind;
use clean_slate_service_fixtures::{
    StorageServiceBootstrap, NETWORK_SERVICE_ID, STORAGE_SERVICE_ID,
    STORAGE_SERVICE_MODE_OBJECT_SERVICE,
};
use clean_slate_service_lifecycle::{
    ControlRequest, ControlRequestKind, InstanceGeneration, LifecycleMessage, ServiceId,
};
use core::sync::atomic::{AtomicBool, AtomicU32, AtomicU64, AtomicUsize, Ordering};

include!(concat!(env!("OUT_DIR"), "/m9_fixture_pins.rs"));

/// One `commands.toml` entry; the table itself is generated by `build.rs`.
struct MatrixCommand {
    name: &'static str,
    /// `export PATH=/bin; <shell>`, byte-identical to the reference harness.
    invocation: &'static [u8],
    exit_status: u8,
    stdout: Option<&'static [u8]>,
    stdout_prefix: Option<&'static [u8]>,
    stdout_contains: &'static [&'static [u8]],
    /// `(path, bytes)` staged under `/tmp` before the first cycle.
    stage: Option<(&'static [u8], &'static [u8])>,
}

include!(concat!(env!("OUT_DIR"), "/m9_command_matrix.rs"));

const MATRIX_LEN: usize = M9_COMMAND_MATRIX.len();
const PASS_MARKER: &str = "[M9.8] PASS";
const SUPERVISOR_PID: u64 = 107;
/// Dedicated RR slot for the native sibling (storage=0, network=1, Linux=2+).
const NATIVE_SLOT: usize = 5;
const USERSPACE_CYCLES: u32 = 9;
const M9_BUSYBOX_STACK_PAGES: u64 = LINUX_CONVENTIONAL_EXEC_STACK_PAGES;
/// Conventional non-PIE x86-64 link window the frozen BusyBox must execute in.
const LOW_VA_ENTRY_RANGE: core::ops::Range<u64> = 0x40_0000..0x80_0000;
const STDOUT_HEX_CHUNK: usize = 32;
/// The unanswered connect must hold its caller asleep across timer ticks, not return
/// from a busy loop.
const CONNECT_TIMEOUT_MIN_BLOCKED_TICKS: u64 = 2;

/// What a probe must demonstrate besides its exit status.
#[derive(Clone, Copy, PartialEq, Eq)]
enum ProbeEvidence {
    /// Write outside the writable `/tmp` projection: `EROFS` from the namespace, no
    /// capability denial involved.
    ReadOnlyProjection,
    /// `/tmp` mutation without the projection grant: capability-layer `op=write` denial.
    TmpWriteDenied,
    /// `/tmp` read without object authority: capability-layer `op=read` denial.
    TmpReadDenied,
    /// `socket(2)` without network authority: `[NET ] denied ... reason=no-authority`.
    NetworkDenied,
    /// Connect to an address the hermetic fixture never answers: the network service's
    /// deadline-driven SYN retransmission gives up and wakes the blocked caller with
    /// `ETIMEDOUT` (checked by the host from BusyBox's stderr).
    ConnectTimeout,
}

struct Probe {
    name: &'static str,
    invocation: &'static [u8],
    authority: LinuxLaunchAuthority,
    exit_status: u64,
    evidence: ProbeEvidence,
}

const NO_TMP: LinuxLaunchAuthority = LinuxLaunchAuthority {
    network: true,
    tmp_objects: false,
};
const NO_NETWORK: LinuxLaunchAuthority = LinuxLaunchAuthority {
    network: false,
    tmp_objects: true,
};

const PROBES: &[Probe] = &[
    Probe {
        name: "deny-fs-readonly",
        invocation: b"export PATH=/bin; echo x > /etc/hostname",
        authority: LinuxLaunchAuthority::FULL,
        exit_status: 1,
        evidence: ProbeEvidence::ReadOnlyProjection,
    },
    Probe {
        name: "deny-tmp-write",
        invocation: b"export PATH=/bin; echo x > /tmp/denied",
        authority: NO_TMP,
        exit_status: 1,
        evidence: ProbeEvidence::TmpWriteDenied,
    },
    Probe {
        name: "deny-tmp-read",
        invocation: b"export PATH=/bin; cat /tmp/script.sh",
        authority: NO_TMP,
        exit_status: 1,
        evidence: ProbeEvidence::TmpReadDenied,
    },
    Probe {
        name: "deny-net",
        invocation: b"export PATH=/bin; wget -O - http://m7.fixture.test:4001/",
        authority: NO_NETWORK,
        exit_status: 1,
        evidence: ProbeEvidence::NetworkDenied,
    },
    Probe {
        name: "connect-timeout",
        invocation: b"export PATH=/bin; wget -O - http://203.0.113.1:9/",
        authority: LinuxLaunchAuthority::FULL,
        exit_status: 1,
        evidence: ProbeEvidence::ConnectTimeout,
    },
];

#[derive(Clone, Copy, PartialEq, Eq)]
enum Phase {
    Command(usize),
    Probe(usize),
}

static M9_PHASE: GlobalCell<Phase> = GlobalCell::new(Phase::Command(0));
static M9_LINUX_PID: AtomicU64 = AtomicU64::new(0);
static M9_CHECKLIST_FAULT: AtomicBool = AtomicBool::new(false);
/// 1-based cycle currently running.
static M9_CYCLE: AtomicU32 = AtomicU32::new(1);
static M9_STDOUT_LEN: AtomicUsize = AtomicUsize::new(0);
const M9_STDOUT_CAP: usize = 4096;
static M9_STDOUT_BUF: GlobalCell<[u8; M9_STDOUT_CAP]> = GlobalCell::new([0; M9_STDOUT_CAP]);
static M9_STDOUT_OPEN: GlobalCell<Option<OpenDescriptionId>> = GlobalCell::new(None);
static BUSYBOX_EXEC_BYTES: GlobalCell<Option<&'static [u8]>> = GlobalCell::new(None);
/// `(stdout_len, fnv)` per matrix command from cycle 1; later cycles must repeat them.
static FIRST_CYCLE_STDOUT: GlobalCell<[(usize, u32); MATRIX_LEN]> =
    GlobalCell::new([(0, 0); MATRIX_LEN]);
static BASELINE: GlobalCell<Option<Resources>> = GlobalCell::new(None);
static FIRST_CYCLE_RESOURCES: GlobalCell<Option<Resources>> = GlobalCell::new(None);

/// `xor eax, eax; syscall; jmp -9`: the native sibling issues `SYSCALL_NR_VERSION` in a
/// loop, so every step it takes is counted by [`observe_native_progress`].
const NATIVE_PROGRESS_CODE: [u8; 6] = [0x31, 0xC0, 0x0F, 0x05, 0xEB, 0xFA];
const NATIVE_PROCESS_STACK: u64 = 0x0000_4000_0000_0000 + PAGE_SIZE * 2;
static NATIVE_PROGRESS: AtomicU64 = AtomicU64::new(0);

/// Linux waits observed during the current command (all its processes).
struct SleepStats {
    blocks: AtomicU32,
    woken: AtomicU32,
    timeouts: AtomicU32,
    cancelled: AtomicU32,
    woken_with_native_progress: AtomicU32,
    timeouts_with_native_progress: AtomicU32,
    native_steps_while_blocked: AtomicU64,
    /// Longest single Linux wait, in timer IRQ ticks.
    max_blocked_ticks: AtomicU64,
}

static SLEEP: SleepStats = SleepStats {
    blocks: AtomicU32::new(0),
    woken: AtomicU32::new(0),
    timeouts: AtomicU32::new(0),
    cancelled: AtomicU32::new(0),
    woken_with_native_progress: AtomicU32::new(0),
    timeouts_with_native_progress: AtomicU32::new(0),
    native_steps_while_blocked: AtomicU64::new(0),
    max_blocked_ticks: AtomicU64::new(0),
};

static SLEEP_ARMED: [AtomicBool; SCHEDULER_THREAD_SLOTS] =
    [const { AtomicBool::new(false) }; SCHEDULER_THREAD_SLOTS];
static SLEEP_NATIVE_AT_BLOCK: [AtomicU64; SCHEDULER_THREAD_SLOTS] =
    [const { AtomicU64::new(0) }; SCHEDULER_THREAD_SLOTS];
static SLEEP_TICKS_AT_BLOCK: [AtomicU64; SCHEDULER_THREAD_SLOTS] =
    [const { AtomicU64::new(0) }; SCHEDULER_THREAD_SLOTS];

static OBJECT_READ_DENIALS: AtomicU32 = AtomicU32::new(0);
static OBJECT_WRITE_DENIALS: AtomicU32 = AtomicU32::new(0);
static NETWORK_DENIALS: AtomicU32 = AtomicU32::new(0);

pub(crate) fn storage_service_bootstrap(
    service: ServiceId,
) -> Result<StorageServiceBootstrap, &'static str> {
    if service != STORAGE_SERVICE_ID {
        return Err("unexpected storage bootstrap service for m9 userspace test");
    }
    Ok(StorageServiceBootstrap::new(
        STORAGE_SERVICE_MODE_OBJECT_SERVICE,
        0,
    ))
}

fn allocator() -> &'static mut PageAllocator {
    service_lifecycle_syscall_allocator_mut()
        .as_mut()
        .unwrap_or_else(|| fatal_kernel_error("m9 userspace allocator missing"))
}

fn phase() -> Phase {
    unsafe { *M9_PHASE.get() }
}

fn set_phase(next: Phase) {
    unsafe { *M9_PHASE.get() = next };
}

fn cycle() -> u32 {
    M9_CYCLE.load(Ordering::Relaxed)
}

fn busybox_image_bytes() -> &'static [u8] {
    unsafe {
        if let Some(bytes) = (*BUSYBOX_EXEC_BYTES.get()).as_ref() {
            return bytes;
        }
        let img = linux_rootfs::image().expect("m9 userspace rootfs");
        let busybox = img.lookup(b"/bin/busybox").expect("busybox");
        assert_eq!(busybox.kind, EntryKind::File);
        let bytes: &'static [u8] = busybox.data;
        *BUSYBOX_EXEC_BYTES.get() = Some(bytes);
        bytes
    }
}

/// The embedded BusyBox must be the pinned build (length + CRC32 recorded by `build.rs`
/// from the SHA-256-verified file) and must still be byte-identical at the end of the run.
fn verify_busybox_bytes(label: &str) {
    let bytes = busybox_image_bytes();
    let crc = clean_slate_rootfs::crc32(bytes);
    if bytes.len() != BUSYBOX_BYTES || crc != BUSYBOX_CRC32 {
        kernel_log_fmt(format_args!(
            "[M9  ] busybox drift {label} bytes={} crc32={crc:#010x} expected_bytes={BUSYBOX_BYTES} expected_crc32={BUSYBOX_CRC32:#010x}\n",
            bytes.len()
        ));
        fatal_kernel_error("m9 userspace busybox bytes drifted");
    }
    kernel_log_fmt(format_args!(
        "[M9  ] busybox {label} bytes={} crc32={crc:#010x} pinned_sha256={BUSYBOX_SHA256} rootfs_sha256={ROOTFS_IMAGE_SHA256}\n",
        bytes.len()
    ));
}

fn install_linux_stdio(pid: u64, generation: InstanceGeneration) {
    let personality = execution_personality_for_pid(pid)
        .unwrap_or_else(|_| fatal_kernel_error("m9 userspace personality"));
    if console_sink_render_style(personality) != ConsoleSinkRenderStyle::Verbatim {
        fatal_kernel_error("m9 userspace stdio not verbatim");
    }
    linux_fd::grant_console_stdio_for_process(pid, generation)
        .unwrap_or_else(|_| fatal_kernel_error("console stdio install"));
    let stdout = linux_fd::open_id_for_fd(pid, generation, 1)
        .unwrap_or_else(|_| fatal_kernel_error("console stdout description"));
    unsafe {
        *M9_STDOUT_OPEN.get() = Some(stdout);
    }
}

fn reset_command_evidence() {
    M9_STDOUT_LEN.store(0, Ordering::Relaxed);
    for counter in [
        &SLEEP.blocks,
        &SLEEP.woken,
        &SLEEP.timeouts,
        &SLEEP.cancelled,
        &SLEEP.woken_with_native_progress,
        &SLEEP.timeouts_with_native_progress,
        &OBJECT_READ_DENIALS,
        &OBJECT_WRITE_DENIALS,
        &NETWORK_DENIALS,
    ] {
        counter.store(0, Ordering::Relaxed);
    }
    SLEEP.native_steps_while_blocked.store(0, Ordering::Relaxed);
    SLEEP.max_blocked_ticks.store(0, Ordering::Relaxed);
}

fn launch_shell(
    allocator: &mut PageAllocator,
    name: &str,
    invocation: &[u8],
    authority: LinuxLaunchAuthority,
) {
    reset_command_evidence();
    let argv: [&[u8]; 3] = [b"/bin/sh", b"-c", invocation];
    let envp: [&[u8]; 1] = [b"PATH=/bin"];
    let spec = LinuxExecSpec {
        image: busybox_image_bytes(),
        argv: &argv,
        envp: &envp,
        exec_filename: b"/bin/sh",
        stack_pages: M9_BUSYBOX_STACK_PAGES,
        policy: &LINUX_CONVENTIONAL_LOAD_POLICY,
    };
    let (slot, stack_top) =
        pick_scheduler_slot_for_relaunch().unwrap_or_else(|m| fatal_kernel_error(m));
    let launched =
        launch_linux_process_with_authority(allocator, stack_top, slot, &spec, authority)
            .unwrap_or_else(|err| {
                kernel_log_fmt(format_args!(
                    "[M9  ] busybox launch err={}\n",
                    err.description()
                ));
                fatal_kernel_error("m9 userspace busybox launch failed");
            });
    if !LOW_VA_ENTRY_RANGE.contains(&launched.entry) {
        fatal_kernel_error("m9 userspace busybox entry outside the conventional low VA window");
    }
    install_linux_stdio(launched.pid, launched.instance_generation);
    M9_LINUX_PID.store(launched.pid, Ordering::Relaxed);
    kernel_log_fmt(format_args!(
        "[M9  ] shell started pid={} slot={} kstack=0x{:x} cmd={} cycle={} entry={:#x} net={} tmp={} stack_pages={}\n",
        launched.pid,
        slot,
        stack_top,
        name,
        cycle(),
        launched.entry,
        authority.network as u8,
        authority.tmp_objects as u8,
        M9_BUSYBOX_STACK_PAGES
    ));
}

fn spawn_native_sibling(allocator: &mut PageAllocator) {
    let stacks = unsafe { &*task_stacks_mut() };
    let native = spawn_native_userspace_process_with_code(
        allocator,
        task_stack_top(&stacks[NATIVE_SLOT]),
        &NATIVE_PROGRESS_CODE,
        NATIVE_PROCESS_STACK,
    )
    .unwrap_or_else(|_| fatal_kernel_error("native sibling"));
    configure_scheduler_thread_slot(NATIVE_SLOT, &native.thread)
        .unwrap_or_else(|_| fatal_kernel_error("native slot"));
}

/// Counts one native-sibling step (its `SYSCALL_NR_VERSION` loop).
pub(crate) fn observe_native_progress() {
    if unsafe { scheduler_mut() }.current_thread == Some(NATIVE_SLOT) {
        NATIVE_PROGRESS.fetch_add(1, Ordering::Relaxed);
    }
}

fn is_linux_pid(pid: u64) -> bool {
    matches!(
        execution_personality_for_pid(pid),
        Ok(ExecutionPersonality::LinuxX86_64)
    )
}

/// A Linux thread entered `ThreadState::Blocked`: remember the native step count.
pub(crate) fn on_thread_blocked(thread_index: usize, pid: u64) {
    if thread_index >= SCHEDULER_THREAD_SLOTS || !is_linux_pid(pid) {
        return;
    }
    SLEEP_NATIVE_AT_BLOCK[thread_index]
        .store(NATIVE_PROGRESS.load(Ordering::Relaxed), Ordering::Relaxed);
    SLEEP_TICKS_AT_BLOCK[thread_index].store(kernel_ticks(), Ordering::Relaxed);
    SLEEP_ARMED[thread_index].store(true, Ordering::Relaxed);
    SLEEP.blocks.fetch_add(1, Ordering::Relaxed);
}

/// A blocked thread became Ready (wake, deadline expiry, or cancel). Runs in IRQ or
/// syscall context: counters only.
pub(crate) fn on_thread_woken(thread_index: usize, outcome: WaitOutcome) {
    if thread_index >= SCHEDULER_THREAD_SLOTS
        || !SLEEP_ARMED[thread_index].swap(false, Ordering::Relaxed)
    {
        return;
    }
    let steps = NATIVE_PROGRESS
        .load(Ordering::Relaxed)
        .saturating_sub(SLEEP_NATIVE_AT_BLOCK[thread_index].load(Ordering::Relaxed));
    SLEEP
        .native_steps_while_blocked
        .fetch_add(steps, Ordering::Relaxed);
    let ticks =
        kernel_ticks().saturating_sub(SLEEP_TICKS_AT_BLOCK[thread_index].load(Ordering::Relaxed));
    SLEEP.max_blocked_ticks.fetch_max(ticks, Ordering::Relaxed);
    let (count, with_progress) = match outcome {
        WaitOutcome::Woken => (&SLEEP.woken, Some(&SLEEP.woken_with_native_progress)),
        WaitOutcome::TimedOut => (&SLEEP.timeouts, Some(&SLEEP.timeouts_with_native_progress)),
        WaitOutcome::Cancelled => (&SLEEP.cancelled, None),
    };
    count.fetch_add(1, Ordering::Relaxed);
    if let Some(with_progress) = with_progress.filter(|_| steps > 0) {
        with_progress.fetch_add(1, Ordering::Relaxed);
    }
}

pub(crate) fn observe_object_denial(write: bool) {
    let counter = if write {
        &OBJECT_WRITE_DENIALS
    } else {
        &OBJECT_READ_DENIALS
    };
    counter.fetch_add(1, Ordering::Relaxed);
}

pub(crate) fn observe_network_denial() {
    NETWORK_DENIALS.fetch_add(1, Ordering::Relaxed);
}

fn log_sleep_stats(name: &str) {
    kernel_log_fmt(format_args!(
        "[M9  ] sleep cmd={name} cycle={} blocks={} woken={} timeouts={} cancelled={} woken_with_native_progress={} timeouts_with_native_progress={} native_steps_while_blocked={} max_blocked_ticks={}\n",
        cycle(),
        SLEEP.blocks.load(Ordering::Relaxed),
        SLEEP.woken.load(Ordering::Relaxed),
        SLEEP.timeouts.load(Ordering::Relaxed),
        SLEEP.cancelled.load(Ordering::Relaxed),
        SLEEP.woken_with_native_progress.load(Ordering::Relaxed),
        SLEEP.timeouts_with_native_progress.load(Ordering::Relaxed),
        SLEEP.native_steps_while_blocked.load(Ordering::Relaxed),
        SLEEP.max_blocked_ticks.load(Ordering::Relaxed),
    ));
}

/// Kernel object occupancy; the reusable part must return to the baseline every cycle.
#[derive(Clone, Copy, PartialEq, Eq)]
struct Resources {
    linux_procs: usize,
    threads: usize,
    processes: usize,
    fd_tables: usize,
    open_files: usize,
    pipes: usize,
    linux_waiters: usize,
    sockets: usize,
    net_requests: usize,
    object_requests: usize,
    capabilities: usize,
    linux_mm: usize,
    linux_signals: usize,
    /// Persistent `/tmp` state: created in cycle 1 by the matrix, then reused.
    tmp_files: usize,
    fs_nodes: usize,
}

impl Resources {
    fn capture() -> Self {
        Self {
            linux_procs: table().occupied(),
            threads: unsafe { scheduler_mut() }.occupied_thread_slots(),
            processes: unsafe { process_registry_mut() }.occupied_slots(),
            fd_tables: linux_fd::fd_table_live_count(),
            open_files: usize::from(open_description_pool_live_count()),
            pipes: pool().live_count(),
            linux_waiters: waiter_occupancy_where(|pid| {
                !matches!(
                    execution_personality_for_pid(pid),
                    Ok(ExecutionPersonality::Native)
                )
            }),
            sockets: crate::process::linux_socket::pool_live_count(),
            net_requests: crate::service::net_bridge::net_bridge_mut().occupied_request_slots(),
            object_requests: crate::capability::object::object_queue_occupied_slots(),
            capabilities: crate::capability::live_capability_count(),
            linux_mm: linux_mem::occupied_slots(),
            linux_signals: crate::process::linux_signal::occupied_slots(),
            tmp_files: tmp_file_live_count(),
            fs_nodes: usize::from(crate::process::linux_fs::table().live_count()),
        }
    }

    fn log(&self, label: &str) {
        kernel_log_fmt(format_args!(
            "[M9  ] resources label={label} linux_procs={} threads={} processes={} fd_tables={} open_files={} pipes={} linux_waiters={} sockets={} net_requests={} object_requests={} capabilities={} linux_mm={} linux_signals={} tmp_files={} fs_nodes={} native_progress={}\n",
            self.linux_procs,
            self.threads,
            self.processes,
            self.fd_tables,
            self.open_files,
            self.pipes,
            self.linux_waiters,
            self.sockets,
            self.net_requests,
            self.object_requests,
            self.capabilities,
            self.linux_mm,
            self.linux_signals,
            self.tmp_files,
            self.fs_nodes,
            NATIVE_PROGRESS.load(Ordering::Relaxed),
        ));
    }

    fn reusable(&self) -> Self {
        Self {
            tmp_files: 0,
            fs_nodes: 0,
            ..*self
        }
    }
}

fn check_cycle_resources(cycle: u32) {
    let now = Resources::capture();
    now.log(if cycle == 1 { "cycle-1" } else { "cycle" });
    let baseline = unsafe { *BASELINE.get() }
        .unwrap_or_else(|| fatal_kernel_error("m9 userspace baseline missing"));
    if now.reusable() != baseline.reusable() {
        fatal_kernel_error("m9 userspace resource drift from baseline");
    }
    let first = unsafe { &mut *FIRST_CYCLE_RESOURCES.get() };
    match first {
        None => *first = Some(now),
        Some(first) if first.tmp_files != now.tmp_files || first.fs_nodes != now.fs_nodes => {
            fatal_kernel_error("m9 userspace persistent tmp state grew after cycle 1");
        }
        Some(_) => {}
    }
}

pub(crate) const fn fnv1a32(bytes: &[u8]) -> u32 {
    let mut hash = 0x811c_9dc5u32;
    let mut index = 0usize;
    while index < bytes.len() {
        hash ^= bytes[index] as u32;
        hash = hash.wrapping_mul(0x0100_0193);
        index += 1;
    }
    hash
}

fn stdout_slice() -> &'static [u8] {
    let len = M9_STDOUT_LEN.load(Ordering::Relaxed);
    let take = len.min(M9_STDOUT_CAP);
    unsafe {
        let buf = &*M9_STDOUT_BUF.get();
        core::slice::from_raw_parts(buf.as_ptr(), take)
    }
}

/// Captures bytes written through the open description installed as the checklist
/// shell's stdout (inherited across fork/dup), matching the reference harness's stdout
/// pipe; stderr diagnostics such as wget progress stay on the console only.
pub(crate) fn observe_console_description_write(open: OpenDescriptionId, bytes: &[u8]) {
    if unsafe { *M9_STDOUT_OPEN.get() } != Some(open) {
        return;
    }
    let len = M9_STDOUT_LEN.load(Ordering::Relaxed);
    let Some(end) = len
        .checked_add(bytes.len())
        .filter(|end| *end <= M9_STDOUT_CAP)
    else {
        fatal_kernel_error("m9 checklist stdout capture exceeded its bound");
    };
    unsafe {
        (&mut *M9_STDOUT_BUF.get())[len..end].copy_from_slice(bytes);
    }
    M9_STDOUT_LEN.store(end, Ordering::Relaxed);
}

fn log_stdout_hex(name: &str, out: &[u8]) {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    for (chunk_index, chunk) in out.chunks(STDOUT_HEX_CHUNK).enumerate() {
        let mut text = [0u8; STDOUT_HEX_CHUNK * 2];
        for (i, byte) in chunk.iter().enumerate() {
            text[i * 2] = HEX[usize::from(byte >> 4)];
            text[i * 2 + 1] = HEX[usize::from(byte & 0xF)];
        }
        let hex = core::str::from_utf8(&text[..chunk.len() * 2]).unwrap_or("?");
        kernel_log_fmt(format_args!(
            "[M9  ] stdout cmd={name} off={} hex={hex}\n",
            chunk_index * STDOUT_HEX_CHUNK
        ));
    }
}

fn contains(haystack: &[u8], needle: &[u8]) -> bool {
    needle.is_empty() || haystack.windows(needle.len()).any(|w| w == needle)
}

fn stdout_matches(cmd: &MatrixCommand, out: &[u8]) -> bool {
    cmd.stdout.is_none_or(|exact| out == exact)
        && cmd
            .stdout_prefix
            .is_none_or(|prefix| out.starts_with(prefix))
        && cmd
            .stdout_contains
            .iter()
            .all(|needle| contains(out, needle))
}

fn finish_matrix_command(index: usize, status: u64) {
    let cmd = &M9_COMMAND_MATRIX[index];
    let cycle = cycle();
    let out = stdout_slice();
    let fnv = fnv1a32(out);
    kernel_log_fmt(format_args!(
        "[M9  ] cmd={} cycle={cycle} status={status} stdout_len={} fnv=0x{fnv:08x}\n",
        cmd.name,
        out.len()
    ));
    log_sleep_stats(cmd.name);
    if status != u64::from(cmd.exit_status) {
        fatal_kernel_error("m9 userspace command exit status");
    }
    if proc_table_invariant_violations() > 0 {
        fatal_kernel_error("m9 userspace proc-table invariant");
    }
    let first = unsafe { &mut (*FIRST_CYCLE_STDOUT.get())[index] };
    if cycle == 1 {
        log_stdout_hex(cmd.name, out);
        if !stdout_matches(cmd, out) {
            fatal_kernel_error("m9 userspace command stdout differs from commands.toml");
        }
        *first = (out.len(), fnv);
    } else if *first != (out.len(), fnv) {
        fatal_kernel_error("m9 userspace command stdout changed across reuse cycles");
    }
    if cycle != 1 {
        return;
    }
    match cmd.name {
        "tmp-file-io" => kernel_log_line("[M9  ] fs PASS"),
        "pipe-grep" => kernel_log_line("[M9  ] process-pipe PASS"),
        "nslookup-fixture" => {
            kernel_log_line("[M9  ] dns PASS");
            let woken = SLEEP.woken_with_native_progress.load(Ordering::Relaxed);
            let ticks = SLEEP.max_blocked_ticks.load(Ordering::Relaxed);
            if woken == 0 || ticks == 0 {
                fatal_kernel_error("m9 userspace DNS wait never slept while native work ran");
            }
            kernel_log_fmt(format_args!(
                "[M9  ] blocking PASS cmd={} woken_with_native_progress={woken} native_steps_while_blocked={} max_blocked_ticks={ticks}\n",
                cmd.name,
                SLEEP.native_steps_while_blocked.load(Ordering::Relaxed)
            ));
        }
        "wget-fixture-http" => kernel_log_line("[M9  ] tcp PASS"),
        _ => {}
    }
}

fn finish_probe(index: usize, pid: u64, status: u64) {
    let probe = &PROBES[index];
    let read_denials = OBJECT_READ_DENIALS.load(Ordering::Relaxed);
    let write_denials = OBJECT_WRITE_DENIALS.load(Ordering::Relaxed);
    let net_denials = NETWORK_DENIALS.load(Ordering::Relaxed);
    kernel_log_fmt(format_args!(
        "[M9  ] probe={} cycle={} pid={pid} status={status} object_read_denials={read_denials} object_write_denials={write_denials} network_denials={net_denials} stdout_len={}\n",
        probe.name,
        cycle(),
        stdout_slice().len()
    ));
    log_sleep_stats(probe.name);
    if status != probe.exit_status {
        fatal_kernel_error("m9 userspace probe exit status");
    }
    if !stdout_slice().is_empty() {
        fatal_kernel_error("m9 userspace probe wrote to stdout");
    }
    let proven = match probe.evidence {
        ProbeEvidence::ReadOnlyProjection => {
            read_denials == 0 && write_denials == 0 && net_denials == 0
        }
        ProbeEvidence::TmpWriteDenied => write_denials > 0 && net_denials == 0,
        ProbeEvidence::TmpReadDenied => read_denials > 0 && write_denials == 0,
        ProbeEvidence::NetworkDenied => net_denials > 0 && read_denials + write_denials == 0,
        ProbeEvidence::ConnectTimeout => {
            SLEEP.woken_with_native_progress.load(Ordering::Relaxed) > 0
                && SLEEP.max_blocked_ticks.load(Ordering::Relaxed)
                    >= CONNECT_TIMEOUT_MIN_BLOCKED_TICKS
        }
    };
    if !proven {
        fatal_kernel_error("m9 userspace probe evidence missing");
    }
    match probe.evidence {
        ProbeEvidence::TmpReadDenied => kernel_log_line("[M9  ] deny fs ok"),
        ProbeEvidence::NetworkDenied => kernel_log_line("[M9  ] deny net ok"),
        ProbeEvidence::ConnectTimeout if cycle() == 1 => {
            kernel_log_fmt(format_args!(
                "[M9  ] timeout PASS cmd={} woken_with_native_progress={} native_steps_while_blocked={} max_blocked_ticks={}\n",
                probe.name,
                SLEEP.woken_with_native_progress.load(Ordering::Relaxed),
                SLEEP.native_steps_while_blocked.load(Ordering::Relaxed),
                SLEEP.max_blocked_ticks.load(Ordering::Relaxed)
            ));
        }
        _ => {}
    }
}

fn dispatch_phase(allocator: &mut PageAllocator) {
    match phase() {
        Phase::Command(index) => {
            let cmd = &M9_COMMAND_MATRIX[index];
            launch_shell(
                allocator,
                cmd.name,
                cmd.invocation,
                LinuxLaunchAuthority::FULL,
            );
        }
        Phase::Probe(index) => {
            let probe = &PROBES[index];
            launch_shell(allocator, probe.name, probe.invocation, probe.authority);
        }
    }
}

fn finish_run() -> ! {
    verify_busybox_bytes("intact");
    kernel_log_line("[M9  ] denial PASS");
    kernel_log_line(PASS_MARKER);
    qemu_exit(QEMU_EXIT_SUCCESS)
}

/// Record a checklist-shell fault; [`checklist_fault_pending`] runs after teardown.
pub(crate) fn on_checklist_command_fault(pid: u64, context: &InterruptContext) {
    if pid != M9_LINUX_PID.load(Ordering::Relaxed) {
        return;
    }
    let name = match phase() {
        Phase::Command(index) => M9_COMMAND_MATRIX[index].name,
        Phase::Probe(index) => PROBES[index].name,
    };
    let cr2 = if context.vector as usize == 14 {
        x86_64::registers::control::Cr2::read()
            .map(|a| a.as_u64())
            .unwrap_or(0)
    } else {
        0
    };
    kernel_log_fmt(format_args!(
        "[M9  ] checklist fault cmd={name} vector={} rip={:#018x} cr2={cr2:#018x}\n",
        context.vector, context.rip
    ));
    if let Some(gen) = live_instance_generation(pid) {
        linux_mem::log_m9_exec_layout(pid, gen, cr2);
    }
    M9_CHECKLIST_FAULT.store(true, Ordering::SeqCst);
}

pub(crate) fn checklist_fault_pending() -> bool {
    M9_CHECKLIST_FAULT.load(Ordering::SeqCst)
}

pub(crate) fn after_linux_exit_group(
    pid: u64,
    teardown: &DomainTeardownResult,
    allocator: &mut PageAllocator,
) -> Option<u64> {
    if pid != M9_LINUX_PID.load(Ordering::Relaxed) {
        return None;
    }
    let next = match phase() {
        Phase::Command(index) => {
            finish_matrix_command(index, teardown.exit_status);
            if index + 1 < MATRIX_LEN {
                Phase::Command(index + 1)
            } else {
                Phase::Probe(0)
            }
        }
        Phase::Probe(index) => {
            finish_probe(index, pid, teardown.exit_status);
            if index + 1 < PROBES.len() {
                Phase::Probe(index + 1)
            } else {
                let finished = cycle();
                check_cycle_resources(finished);
                kernel_log_fmt(format_args!("[M9  ] cycle={finished}\n"));
                if finished >= USERSPACE_CYCLES {
                    finish_run();
                }
                M9_CYCLE.store(finished + 1, Ordering::Relaxed);
                Phase::Command(0)
            }
        }
    };
    set_phase(next);
    dispatch_phase(allocator);
    Some(start_current_scheduler_thread().unwrap_or_else(|m| fatal_kernel_error(m)))
}

fn launch_storage_service(
    controller: &mut ServiceLifecycleController,
    allocator: &mut PageAllocator,
    lifecycle_capability: u64,
) {
    let result = controller
        .handle_control_message(
            allocator,
            SUPERVISOR_PID,
            lifecycle_capability,
            &LifecycleMessage::ControlRequest(ControlRequest::new(
                STORAGE_SERVICE_ID,
                ControlRequestKind::Start,
            ))
            .encode(),
        )
        .unwrap_or_else(|_| fatal_kernel_error("m9 userspace storage launch failed"));
    let pid = result
        .event
        .map(|event| event.instance.pid.0)
        .unwrap_or_else(|| fatal_kernel_error("storage pid missing"));
    kernel_log_fmt(format_args!("[STOR] object-service started pid={pid}\n"));
}

fn launch_network_service(
    controller: &mut ServiceLifecycleController,
    allocator: &mut PageAllocator,
    lifecycle_capability: u64,
) {
    let _ = controller
        .handle_control_message(
            allocator,
            SUPERVISOR_PID,
            lifecycle_capability,
            &LifecycleMessage::ControlRequest(ControlRequest::new(
                NETWORK_SERVICE_ID,
                ControlRequestKind::Start,
            ))
            .encode(),
        )
        .unwrap_or_else(|_| fatal_kernel_error("m9 userspace network launch failed"));
}

pub(crate) fn start_m9_userspace_self_test(page_allocator: PageAllocator) -> ! {
    kernel_log_line("[M9  ] creating");
    install_service_lifecycle_syscall_allocator(page_allocator);
    reset_process_scheduler_world();
    unsafe {
        *id_allocator_mut() = IdAllocator::new();
        process_registry_mut().clear();
        *scheduler_mut() = Scheduler::new();
    }
    linux_fd::reset_registry_for_selftest();

    let img = linux_rootfs::image().expect("rootfs");
    crate::process::linux_fs::init_namespace(&img).expect("namespace");
    linux_rootfs::ensure_rootfs_integrity_logged().expect("integrity");
    verify_busybox_bytes("verified");
    kernel_log_fmt(format_args!(
        "[M9  ] matrix commands={MATRIX_LEN} probes={} cycles={USERSPACE_CYCLES}\n",
        PROBES.len()
    ));
    for cmd in M9_COMMAND_MATRIX {
        if let Some((path, body)) = cmd.stage {
            bootstrap_tmp_file_bytes(path, body)
                .unwrap_or_else(|_| fatal_kernel_error("m9 userspace stage file"));
        }
    }

    let allocator = allocator();
    let kernel_root = current_root_frame_address();
    let kernel_stack_top = unsafe { task_stack_top(&(*task_stacks_mut())[0]) };
    set_privilege_stack(kernel_stack_top).unwrap_or_else(|m| fatal_kernel_error(m));
    initialize_syscall_abi(kernel_stack_top).unwrap_or_else(|m| fatal_kernel_error(m));

    let controller = unsafe { service_lifecycle_controller_mut() };
    controller.clear();
    controller.configure_launch_context(kernel_root);
    controller
        .declare_service(STORAGE_SERVICE_ID)
        .unwrap_or_else(|m| fatal_kernel_error(m));
    controller
        .declare_service(NETWORK_SERVICE_ID)
        .unwrap_or_else(|m| fatal_kernel_error(m));
    let lifecycle_capability = controller
        .grant_lifecycle_control_capability(SUPERVISOR_PID)
        .unwrap_or_else(|m| fatal_kernel_error(m));

    launch_storage_service(controller, allocator, lifecycle_capability);
    crate::selftest::m7_net_service::init_minimal_state_for_m9_socket(lifecycle_capability);
    launch_network_service(controller, allocator, lifecycle_capability);
    crate::process::linux_socket::grant_linux_network_capabilities(SUPERVISOR_PID)
        .unwrap_or_else(|_| fatal_kernel_error("network grant"));

    spawn_native_sibling(allocator);
    let baseline = Resources::capture();
    baseline.log("baseline");
    unsafe { *BASELINE.get() = Some(baseline) };

    initialize_timer();
    // `m3-entry-self-test` skips calibration inside `initialize_timer`; the net service's
    // WAIT_WORK/RX deadlines and Linux `nanosleep` use TSC `MonotonicNs` deadlines.
    crate::time::calibration::calibrate_apic_tick();
    kernel_log_line("[TIME] timer initialized");

    set_phase(Phase::Command(0));
    dispatch_phase(allocator);
    let frame = start_current_scheduler_thread().unwrap_or_else(|m| fatal_kernel_error(m));
    unsafe { restore_task_context(frame) }
}
