[package]
name = "clean-slate-kernel"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[features]
gdb-entry = []
m1-self-test = []
m2-double-fault-self-test = []
m2-self-test = []
m2-timer-self-test = []
m3-address-space-self-test = []
m3-entry-self-test = []
m3-resources-self-test = []
m3-syscall-self-test = ["m3-entry-self-test"]
m3-ipc-self-test = ["m3-entry-self-test"]
m4-crash-service-self-test = []
m4-service-lifecycle-self-test = ["m3-entry-self-test"]
m4-supervisor-self-test = ["m3-entry-self-test"]
m4-recovery-self-test = []
m5-storage-self-test = ["m3-entry-self-test"]

[lib]
path = "src/lib.rs"

[[bin]]
name = "clean-slate-kernel"
path = "src/main.rs"
test = false

[dependencies]
clean-slate-block = { path = "../block" }
clean-slate-service-fixtures = { path = "../service-fixtures" }
clean-slate-service-lifecycle = { path = "../service-lifecycle" }
uefi = "0.37.0"
x86_64 = { version = "0.15.5", default-features = false, features = ["instructions"] }

[lints]
workspace = true
