//! Generic transactional userspace image segment mapper.
//!
//! Consumes build-time embedded segment tables (native images) or a
//! [`clean_slate_elf::LoadPlan`] (future Linux path in #92). Maps file-backed
//! bytes, zero-fills `memsz - filesz` (including the partial final file page),
//! applies segment-derived R/W/X flags under W^X, merges same-page PT_LOAD
//! contributions, and rolls back on failure.

#![allow(dead_code)]

use crate::mm::address_space::{map_process_page, unmap_last_user_mapping, ProcessAddressSpace};
use crate::mm::frame_allocator::{free_frame, PageAllocator};
use crate::mm::paging::zero_page;
use crate::mm::{PAGE_SIZE, PHYSICAL_MEMORY_OFFSET};
use clean_slate_elf::{SegmentPermissions, MAX_LOAD_SEGMENTS, PF_R, PF_W, PF_X};
use core::ptr;
use x86_64::structures::paging::PageTableFlags;

/// Upper bound on unique image pages tracked during a single map call.
/// Matches the largest deliberate `MAX_ADDRESS_SPACE_USER_MAPPINGS` (M7 network).
const MAX_IMAGE_MAP_PAGES: usize = 384;

/// One embedded PT_LOAD description generated by `kernel/build.rs`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct EmbeddedSegment {
    /// Virtual address offset from the process image load base.
    pub offset_from_base: u64,
    pub filesz: u64,
    pub memsz: u64,
    /// Offset into the embedded file-backed byte blob.
    pub file_offset: u64,
    /// ELF `p_flags` low bits (`PF_R`/`PF_W`/`PF_X`).
    pub flags: u8,
}

impl EmbeddedSegment {
    pub(crate) fn permissions(&self) -> SegmentPermissions {
        SegmentPermissions {
            read: (self.flags & PF_R as u8) != 0,
            write: (self.flags & PF_W as u8) != 0,
            execute: (self.flags & PF_X as u8) != 0,
        }
    }
}

/// Page-table flags for userspace image pages. Never maps W+X.
pub(crate) fn page_flags_for_segment_perms(
    perms: SegmentPermissions,
) -> Result<PageTableFlags, &'static str> {
    if perms.is_write_execute() {
        return Err("refusing to map a write+execute userspace page");
    }
    let mut flags = PageTableFlags::PRESENT | PageTableFlags::USER_ACCESSIBLE;
    if perms.write {
        flags |= PageTableFlags::WRITABLE;
    }
    if !perms.execute {
        flags |= PageTableFlags::NO_EXECUTE;
    }
    Ok(flags)
}

#[derive(Clone, Copy)]
struct PagePlan {
    page_vaddr: u64,
    perms: SegmentPermissions,
    present: bool,
}

/// Exact unique mapped-page demand for an embedded segment table.
pub(crate) fn embedded_mapped_page_count(
    segments: &[EmbeddedSegment],
) -> Result<usize, &'static str> {
    let mut pages = [PagePlan {
        page_vaddr: 0,
        perms: SegmentPermissions::default(),
        present: false,
    }; MAX_IMAGE_MAP_PAGES];
    let count = collect_unique_pages(0, segments, &mut pages)?;
    Ok(count)
}

fn collect_unique_pages(
    load_base: u64,
    segments: &[EmbeddedSegment],
    pages: &mut [PagePlan],
) -> Result<usize, &'static str> {
    let mut count = 0usize;
    for segment in segments {
        if segment.memsz == 0 {
            continue;
        }
        if segment.filesz > segment.memsz {
            return Err("embedded segment filesz exceeds memsz");
        }
        let vaddr = load_base
            .checked_add(segment.offset_from_base)
            .ok_or("segment load address overflow")?;
        let page_count = segment_mapped_pages(vaddr, segment.memsz)?;
        let first_page = vaddr & !(PAGE_SIZE - 1);
        let seg_perms = segment.permissions();
        for page_index in 0..page_count {
            let page_vaddr = first_page
                .checked_add(
                    (page_index as u64)
                        .checked_mul(PAGE_SIZE)
                        .ok_or("page index overflow")?,
                )
                .ok_or("page vaddr overflow")?;
            match pages[..count]
                .iter_mut()
                .find(|page| page.present && page.page_vaddr == page_vaddr)
            {
                Some(existing) => {
                    existing.perms.read |= seg_perms.read;
                    existing.perms.write |= seg_perms.write;
                    existing.perms.execute |= seg_perms.execute;
                }
                None => {
                    if count >= pages.len() {
                        return Err("image page plan capacity exceeded");
                    }
                    pages[count] = PagePlan {
                        page_vaddr,
                        perms: seg_perms,
                        present: true,
                    };
                    count += 1;
                }
            }
        }
    }
    for page in pages[..count].iter() {
        if page.perms.is_write_execute() {
            return Err("image page would be writable and executable");
        }
    }
    Ok(count)
}

fn segment_mapped_pages(vaddr: u64, memsz: u64) -> Result<usize, &'static str> {
    if memsz == 0 {
        return Ok(0);
    }
    let end = vaddr.checked_add(memsz).ok_or("segment memsz overflow")?;
    let first = vaddr & !(PAGE_SIZE - 1);
    let last_exclusive = align_up(end, PAGE_SIZE)?;
    let bytes = last_exclusive
        .checked_sub(first)
        .ok_or("segment page span underflow")?;
    usize::try_from(bytes / PAGE_SIZE).map_err(|_| "segment page count too large")
}

fn align_up(value: u64, align: u64) -> Result<u64, &'static str> {
    if value & (align - 1) == 0 {
        Ok(value)
    } else {
        value
            .checked_add(align - (value & (align - 1)))
            .ok_or("align_up overflow")
    }
}

/// Map `segments` at `load_base` from `file_bytes`, returning the number of pages mapped.
///
/// On any failure, all pages mapped by this call are unmapped and their frames freed.
pub(crate) fn map_embedded_segments(
    address_space: &mut ProcessAddressSpace,
    allocator: &mut PageAllocator,
    load_base: u64,
    file_bytes: &[u8],
    segments: &[EmbeddedSegment],
) -> Result<usize, &'static str> {
    let mut pages = [PagePlan {
        page_vaddr: 0,
        perms: SegmentPermissions::default(),
        present: false,
    }; MAX_IMAGE_MAP_PAGES];
    let page_count = collect_unique_pages(load_base, segments, &mut pages)?;
    let mut mapped = 0usize;
    let result = map_unique_pages(
        address_space,
        allocator,
        load_base,
        file_bytes,
        segments,
        &pages[..page_count],
        &mut mapped,
    );
    if result.is_err() {
        while mapped > 0 {
            unmap_last_user_mapping(address_space, allocator)?;
            mapped -= 1;
        }
    }
    result.map(|_| mapped)
}

fn map_unique_pages(
    address_space: &mut ProcessAddressSpace,
    allocator: &mut PageAllocator,
    load_base: u64,
    file_bytes: &[u8],
    segments: &[EmbeddedSegment],
    pages: &[PagePlan],
    mapped: &mut usize,
) -> Result<(), &'static str> {
    for page in pages {
        if page.page_vaddr < PAGE_SIZE {
            return Err("refusing to map userspace page zero");
        }
        let flags = page_flags_for_segment_perms(page.perms)?;
        let frame = allocator
            .allocate_page()
            .ok_or("allocator could not provide an image page")?;
        zero_page(frame);
        for segment in segments {
            if segment.memsz == 0 {
                continue;
            }
            let seg_vaddr = load_base
                .checked_add(segment.offset_from_base)
                .ok_or("segment load address overflow")?;
            let seg_end = seg_vaddr
                .checked_add(segment.memsz)
                .ok_or("segment memsz overflow")?;
            let page_end = page
                .page_vaddr
                .checked_add(PAGE_SIZE)
                .ok_or("page end overflow")?;
            if seg_vaddr >= page_end || page.page_vaddr >= seg_end {
                continue;
            }
            fill_page_from_segment(frame, page.page_vaddr, seg_vaddr, segment, file_bytes)?;
        }
        if let Err(message) =
            map_process_page(address_space, page.page_vaddr, frame, flags, allocator)
        {
            unsafe {
                let _ = free_frame(allocator, frame);
            }
            return Err(message);
        }
        *mapped += 1;
    }
    Ok(())
}

/// File-backed byte span of one mapped page for one segment.
///
/// Everything in the page outside `[page_offset, page_offset + len)` that the
/// segment covers is BSS and stays at the zero-fill value written by
/// `zero_page`. This is the pure decision behind `fill_page_from_segment`
/// (host-tested; the copy itself needs a live frame).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct PageFileSpan {
    /// Byte offset inside the page where file bytes start.
    pub(crate) page_offset: usize,
    /// Byte offset relative to the segment's first file byte (`p_offset`).
    pub(crate) file_rel: usize,
    /// Number of file-backed bytes to copy into this page.
    pub(crate) len: usize,
}

/// Decide which bytes of the page at `page_vaddr` are file-backed for a segment
/// whose first byte lives at `segment_vaddr` with `filesz` file bytes.
///
/// Returns `Ok(None)` when the page holds no file bytes for this segment (pure
/// BSS page, or `filesz == 0`). Never reads memory; checked arithmetic only.
pub(crate) fn page_file_span(
    page_vaddr: u64,
    segment_vaddr: u64,
    filesz: u64,
) -> Result<Option<PageFileSpan>, &'static str> {
    if filesz == 0 {
        return Ok(None);
    }
    let file_vaddr_end = segment_vaddr
        .checked_add(filesz)
        .ok_or("segment filesz overflow")?;
    let page_end = page_vaddr
        .checked_add(PAGE_SIZE)
        .ok_or("page end overflow")?;

    let copy_start = page_vaddr.max(segment_vaddr);
    let copy_end = page_end.min(file_vaddr_end);
    if copy_start >= copy_end {
        return Ok(None);
    }
    let page_offset =
        usize::try_from(copy_start - page_vaddr).map_err(|_| "page offset overflow")?;
    let file_rel =
        usize::try_from(copy_start - segment_vaddr).map_err(|_| "file offset overflow")?;
    let len = usize::try_from(copy_end - copy_start).map_err(|_| "copy length overflow")?;
    Ok(Some(PageFileSpan {
        page_offset,
        file_rel,
        len,
    }))
}

fn fill_page_from_segment(
    frame: u64,
    page_vaddr: u64,
    segment_vaddr: u64,
    segment: &EmbeddedSegment,
    file_bytes: &[u8],
) -> Result<(), &'static str> {
    let Some(span) = page_file_span(page_vaddr, segment_vaddr, segment.filesz)? else {
        return Ok(());
    };
    let blob_off = usize::try_from(segment.file_offset)
        .ok()
        .and_then(|base| base.checked_add(span.file_rel))
        .ok_or("file blob offset overflow")?;
    let blob_end = blob_off
        .checked_add(span.len)
        .ok_or("file blob end overflow")?;
    if blob_end > file_bytes.len() {
        return Err("embedded segment file range exceeded image blob");
    }
    unsafe {
        ptr::copy_nonoverlapping(
            file_bytes[blob_off..blob_end].as_ptr(),
            ((PHYSICAL_MEMORY_OFFSET + frame) as *mut u8).wrapping_add(span.page_offset),
            span.len,
        );
    }
    Ok(())
}

/// Map a validated [`clean_slate_elf::LoadPlan`] from a full ELF file byte source.
///
/// Intended for the Linux runtime loader (#92). File bytes are read from
/// `elf_bytes` at each segment's `file_offset`; virtual addresses are absolute.
pub(crate) fn map_load_plan_segments(
    address_space: &mut ProcessAddressSpace,
    allocator: &mut PageAllocator,
    elf_bytes: &[u8],
    plan: &clean_slate_elf::LoadPlan,
) -> Result<usize, &'static str> {
    let mut embedded = [EmbeddedSegment {
        offset_from_base: 0,
        filesz: 0,
        memsz: 0,
        file_offset: 0,
        flags: 0,
    }; MAX_LOAD_SEGMENTS];
    let image_base = plan.image_base().ok_or("load plan has no segments")?;
    for (index, segment) in plan.iter_segments().enumerate() {
        let offset_from_base = segment
            .vaddr
            .checked_sub(image_base)
            .ok_or("load-plan segment below image base")?;
        let mut flags = 0u8;
        if segment.perms.read {
            flags |= PF_R as u8;
        }
        if segment.perms.write {
            flags |= PF_W as u8;
        }
        if segment.perms.execute {
            flags |= PF_X as u8;
        }
        embedded[index] = EmbeddedSegment {
            offset_from_base,
            filesz: segment.filesz,
            memsz: segment.memsz,
            file_offset: segment.file_offset,
            flags,
        };
    }
    map_embedded_segments(
        address_space,
        allocator,
        image_base,
        elf_bytes,
        &embedded[..plan.segment_count],
    )
}

/// Userspace stack pages: writable, non-executable.
pub(crate) fn map_user_stack_pages(
    address_space: &mut ProcessAddressSpace,
    allocator: &mut PageAllocator,
    stack_base: u64,
    page_count: u64,
) -> Result<usize, &'static str> {
    let flags = PageTableFlags::PRESENT
        | PageTableFlags::WRITABLE
        | PageTableFlags::NO_EXECUTE
        | PageTableFlags::USER_ACCESSIBLE;
    let mut mapped = 0usize;
    for stack_page in 0..page_count {
        let frame = match allocator.allocate_page() {
            Some(frame) => frame,
            None => {
                while mapped > 0 {
                    unmap_last_user_mapping(address_space, allocator)?;
                    mapped -= 1;
                }
                return Err("allocator could not provide a stack page");
            }
        };
        zero_page(frame);
        let vaddr = stack_base
            .checked_add(stack_page * PAGE_SIZE)
            .ok_or("stack page address overflow")?;
        if let Err(message) = map_process_page(address_space, vaddr, frame, flags, allocator) {
            unsafe {
                let _ = free_frame(allocator, frame);
            }
            while mapped > 0 {
                unmap_last_user_mapping(address_space, allocator)?;
                mapped -= 1;
            }
            return Err(message);
        }
        mapped += 1;
    }
    Ok(mapped)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn page_flags_reject_write_execute() {
        let err = page_flags_for_segment_perms(SegmentPermissions {
            read: true,
            write: true,
            execute: true,
        });
        assert_eq!(err, Err("refusing to map a write+execute userspace page"));
    }

    #[test]
    fn page_flags_executable_are_not_nx() {
        let flags = page_flags_for_segment_perms(SegmentPermissions {
            read: true,
            write: false,
            execute: true,
        })
        .unwrap();
        assert!(flags.contains(PageTableFlags::PRESENT));
        assert!(flags.contains(PageTableFlags::USER_ACCESSIBLE));
        assert!(!flags.contains(PageTableFlags::WRITABLE));
        assert!(!flags.contains(PageTableFlags::NO_EXECUTE));
    }

    #[test]
    fn page_flags_writable_are_nx() {
        let flags = page_flags_for_segment_perms(SegmentPermissions {
            read: true,
            write: true,
            execute: false,
        })
        .unwrap();
        assert!(flags.contains(PageTableFlags::WRITABLE));
        assert!(flags.contains(PageTableFlags::NO_EXECUTE));
    }

    #[test]
    fn embedded_mapped_page_count_includes_bss_pages() {
        let segments = [EmbeddedSegment {
            offset_from_base: 0,
            filesz: 0x10,
            memsz: PAGE_SIZE + 0x20,
            file_offset: 0,
            flags: PF_R as u8 | PF_W as u8,
        }];
        assert_eq!(embedded_mapped_page_count(&segments).unwrap(), 2);
    }

    #[test]
    fn embedded_mapped_page_count_dedups_shared_readonly_page() {
        let segments = [
            EmbeddedSegment {
                offset_from_base: 0,
                filesz: 0x100,
                memsz: 0x100,
                file_offset: 0,
                flags: PF_R as u8 | PF_X as u8,
            },
            EmbeddedSegment {
                offset_from_base: 0x200,
                filesz: 0x100,
                memsz: 0x100,
                file_offset: 0x200,
                flags: PF_R as u8,
            },
        ];
        assert_eq!(embedded_mapped_page_count(&segments).unwrap(), 1);
    }

    #[test]
    fn shared_page_rx_and_rw_is_rejected() {
        let segments = [
            EmbeddedSegment {
                offset_from_base: 0,
                filesz: 0x100,
                memsz: 0x100,
                file_offset: 0,
                flags: PF_R as u8 | PF_X as u8,
            },
            EmbeddedSegment {
                offset_from_base: 0x200,
                filesz: 0x100,
                memsz: 0x100,
                file_offset: 0x200,
                flags: PF_R as u8 | PF_W as u8,
            },
        ];
        assert_eq!(
            embedded_mapped_page_count(&segments),
            Err("image page would be writable and executable")
        );
    }

    #[test]
    fn segment_page_span_partial_first_page() {
        assert_eq!(segment_mapped_pages(0x100, 0x100).unwrap(), 1);
        assert_eq!(segment_mapped_pages(0x100, PAGE_SIZE).unwrap(), 2);
    }

    /// Segment with `memsz > filesz`: 0x10 file bytes then BSS running into a
    /// second page. Page 0 gets a partial file copy (rest zero); page 1 is all zero.
    #[test]
    fn page_file_span_partial_tail_page_then_pure_bss_page() {
        let base = 0x0000_4000_0040_0000u64;
        let filesz = 0x10u64;
        assert_eq!(
            page_file_span(base, base, filesz).unwrap(),
            Some(PageFileSpan {
                page_offset: 0,
                file_rel: 0,
                len: 0x10,
            })
        );
        // Second page of a memsz = PAGE_SIZE + 0x20 segment: zero-fill only.
        assert_eq!(
            page_file_span(base + PAGE_SIZE, base, filesz).unwrap(),
            None
        );
    }

    /// File bytes span a page boundary: page 0 copies from the segment start to
    /// its end, page 1 copies the remaining tail at page offset 0.
    #[test]
    fn page_file_span_crosses_page_boundary() {
        let base = 0x0000_4000_0040_0100u64;
        let filesz = PAGE_SIZE; // ends 0x100 into the next page
        let page0 = base & !(PAGE_SIZE - 1);
        assert_eq!(
            page_file_span(page0, base, filesz).unwrap(),
            Some(PageFileSpan {
                page_offset: 0x100,
                file_rel: 0,
                len: (PAGE_SIZE - 0x100) as usize,
            })
        );
        assert_eq!(
            page_file_span(page0 + PAGE_SIZE, base, filesz).unwrap(),
            Some(PageFileSpan {
                page_offset: 0,
                file_rel: (PAGE_SIZE - 0x100) as usize,
                len: 0x100,
            })
        );
        // Third page is beyond the file bytes.
        assert_eq!(
            page_file_span(page0 + 2 * PAGE_SIZE, base, filesz).unwrap(),
            None
        );
    }

    #[test]
    fn page_file_span_zero_filesz_is_never_file_backed() {
        assert_eq!(page_file_span(0x1000, 0x1000, 0).unwrap(), None);
    }

    #[test]
    fn page_file_span_rejects_overflow() {
        assert_eq!(
            page_file_span(0x1000, u64::MAX - 8, 0x10),
            Err("segment filesz overflow")
        );
    }
}
