//! BDF → `raster/src/font/spleen_8x16.rs` generator (`cargo xtask gen-raster-font`).

use crate::m8_fixture;

const CELL_W: usize = 8;
const CELL_H: usize = 16;
const FIRST: u32 = 0x20;
const LAST: u32 = 0x7E;

pub(crate) fn generate(bdf: &str) -> Result<String, String> {
    let font_ascent = parse_font_ascent(bdf)?;
    let (fbbox_w, fbbox_h, _, _) = parse_font_bounding_box(bdf)?;
    if fbbox_w != CELL_W as i32 || fbbox_h != CELL_H as i32 {
        return Err(format!(
            "expected FONTBOUNDINGBOX {CELL_W} {CELL_H}, got {fbbox_w} {fbbox_h}"
        ));
    }

    let mut glyphs = [[0u8; CELL_H]; (LAST - FIRST + 1) as usize];
    let mut replacement: Option<[u8; CELL_H]> = None;
    let mut question: Option<[u8; CELL_H]> = None;

    for block in char_blocks(bdf) {
        let encoding = parse_encoding(&block)?;
        let (bbx_w, bbx_h, bbx_xoff, bbx_yoff, bitmap_rows) = parse_glyph_block(&block)?;
        if bbx_w != CELL_W as i32 {
            return Err(format!("encoding {encoding}: width {bbx_w} != {CELL_W}"));
        }
        if bitmap_rows.len() != bbx_h as usize {
            return Err(format!(
                "encoding {encoding}: bitmap rows {} != BBX height {bbx_h}",
                bitmap_rows.len()
            ));
        }
        let rows = place_in_cell(font_ascent, bbx_h, bbx_xoff, bbx_yoff, &bitmap_rows)?;
        if encoding == 0xFFFD {
            replacement = Some(rows);
        }
        if encoding == b'?' as u32 {
            question = Some(rows);
        }
        if (FIRST..=LAST).contains(&encoding) {
            let idx = (encoding - FIRST) as usize;
            glyphs[idx] = rows;
        }
    }

    for (i, code) in (FIRST..=LAST).enumerate() {
        if glyphs[i] == [0u8; CELL_H] && code != 0x20 {
            return Err(format!("missing glyph for encoding {code}"));
        }
    }

    let replacement = replacement
        .or(question)
        .ok_or_else(|| "no U+FFFD or '?' replacement glyph".to_string())?;

    let bdf_sha = m8_fixture::sha256(bdf.as_bytes());
    let bdf_hex = hex_bytes(&bdf_sha);

    let mut out = String::new();
    out.push_str("// @generated by `cargo xtask gen-raster-font`; do not edit.\n");
    out.push_str(
        "// Spleen 2.1.0 by Frederic Cambus, BSD-2-Clause, see raster/fonts/LICENSE.spleen\n",
    );
    out.push_str(&format!("// BDF SHA-256: {bdf_hex}\n"));
    out.push('\n');
    out.push_str(&format!("pub(crate) const ASCENT: u32 = {font_ascent};\n"));
    out.push('\n');
    out.push_str("pub(crate) static GLYPHS: [[u8; 16]; 95] = [\n");
    for row in &glyphs {
        out.push_str("    [");
        for (j, byte) in row.iter().enumerate() {
            if j > 0 {
                out.push_str(", ");
            }
            out.push_str(&format!("0x{byte:02X}"));
        }
        out.push_str("],\n");
    }
    out.push_str("];\n");
    out.push('\n');
    out.push_str("pub(crate) static REPLACEMENT: [u8; 16] = [");
    for (j, byte) in replacement.iter().enumerate() {
        if j > 0 {
            out.push_str(", ");
        }
        out.push_str(&format!("0x{byte:02X}"));
    }
    out.push_str("];\n");
    Ok(out)
}

fn hex_bytes(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut out = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        out.push(HEX[(b >> 4) as usize] as char);
        out.push(HEX[(b & 0xf) as usize] as char);
    }
    out
}

fn parse_font_ascent(bdf: &str) -> Result<u32, String> {
    for line in bdf.lines() {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix("FONT_ASCENT ") {
            return rest
                .split_whitespace()
                .next()
                .ok_or_else(|| "FONT_ASCENT empty".to_string())?
                .parse::<u32>()
                .map_err(|e| format!("FONT_ASCENT: {e}"));
        }
    }
    Err("FONT_ASCENT not found".to_string())
}

fn parse_font_bounding_box(bdf: &str) -> Result<(i32, i32, i32, i32), String> {
    for line in bdf.lines() {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix("FONTBOUNDINGBOX ") {
            let parts: Vec<&str> = rest.split_whitespace().collect();
            if parts.len() < 4 {
                return Err("FONTBOUNDINGBOX too short".to_string());
            }
            let w: i32 = parts[0]
                .parse()
                .map_err(|e| format!("FONTBOUNDINGBOX w: {e}"))?;
            let h: i32 = parts[1]
                .parse()
                .map_err(|e| format!("FONTBOUNDINGBOX h: {e}"))?;
            let x: i32 = parts[2]
                .parse()
                .map_err(|e| format!("FONTBOUNDINGBOX x: {e}"))?;
            let y: i32 = parts[3]
                .parse()
                .map_err(|e| format!("FONTBOUNDINGBOX y: {e}"))?;
            return Ok((w, h, x, y));
        }
    }
    Err("FONTBOUNDINGBOX not found".to_string())
}

fn char_blocks(bdf: &str) -> Vec<String> {
    let lines: Vec<&str> = bdf.lines().collect();
    let mut blocks = Vec::new();
    let mut i = 0;
    while i < lines.len() {
        if lines[i].starts_with("STARTCHAR ") {
            let start = i;
            while i < lines.len() && !lines[i].starts_with("ENDCHAR") {
                i += 1;
            }
            if i < lines.len() {
                blocks.push(lines[start..=i].join("\n"));
            }
        }
        i += 1;
    }
    blocks
}

fn parse_encoding(block: &str) -> Result<u32, String> {
    for line in block.lines() {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix("ENCODING ") {
            return rest
                .split_whitespace()
                .next()
                .ok_or_else(|| "ENCODING empty".to_string())?
                .parse::<u32>()
                .map_err(|e| format!("ENCODING: {e}"));
        }
    }
    Err("ENCODING not found in glyph block".to_string())
}

fn parse_glyph_block(block: &str) -> Result<(i32, i32, i32, i32, Vec<u8>), String> {
    let mut bbx: Option<(i32, i32, i32, i32)> = None;
    let mut in_bitmap = false;
    let mut hex_rows: Vec<String> = Vec::new();
    for line in block.lines() {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix("BBX ") {
            let parts: Vec<&str> = rest.split_whitespace().collect();
            if parts.len() < 4 {
                return Err("BBX too short".to_string());
            }
            let w: i32 = parts[0].parse().map_err(|e| format!("BBX w: {e}"))?;
            let h: i32 = parts[1].parse().map_err(|e| format!("BBX h: {e}"))?;
            let x: i32 = parts[2].parse().map_err(|e| format!("BBX x: {e}"))?;
            let y: i32 = parts[3].parse().map_err(|e| format!("BBX y: {e}"))?;
            bbx = Some((w, h, x, y));
        } else if trimmed == "BITMAP" {
            in_bitmap = true;
        } else if in_bitmap {
            if trimmed.starts_with("ENDCHAR") {
                break;
            }
            hex_rows.push(trimmed.to_string());
        }
    }
    let (w, h, x, y) = bbx.ok_or_else(|| "BBX missing".to_string())?;
    let mut bitmap_rows = Vec::with_capacity(hex_rows.len());
    for hex in hex_rows {
        bitmap_rows.push(parse_hex_row(&hex, w as usize)?);
    }
    Ok((w, h, x, y, bitmap_rows))
}

fn parse_hex_row(hex: &str, width: usize) -> Result<u8, String> {
    if hex.is_empty() {
        return Ok(0);
    }
    let value = u8::from_str_radix(hex, 16).map_err(|e| format!("BITMAP hex '{hex}': {e}"))?;
    let needed_bits = width;
    let shift = 8usize.saturating_sub(needed_bits);
    Ok(value << shift)
}

fn place_in_cell(
    _font_ascent: u32,
    bbx_h: i32,
    bbx_xoff: i32,
    _bbx_yoff: i32,
    bitmap_rows: &[u8],
) -> Result<[u8; CELL_H], String> {
    if bbx_xoff != 0 {
        return Err(format!("non-zero BBX xoff {bbx_xoff} unsupported"));
    }
    if bbx_h as usize != bitmap_rows.len() {
        return Err("BBX height mismatch".to_string());
    }
    let mut cell = [0u8; CELL_H];
    if bitmap_rows.len() == CELL_H {
        for (i, &bits) in bitmap_rows.iter().enumerate() {
            cell[i] = bits;
        }
        return Ok(cell);
    }
    Err(format!(
        "glyph height {} != cell height {CELL_H}",
        bitmap_rows.len()
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::path::PathBuf;
    use std::process::Command;

    fn workspace_root() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .expect("xtask in workspace")
            .to_path_buf()
    }

    fn rustfmt_source(source: &str) -> String {
        let path = std::env::temp_dir().join(format!(
            "clean-slate-raster-font-gen-{}.rs",
            std::process::id()
        ));
        fs::write(&path, source).expect("write temp");
        let status = Command::new("rustfmt")
            .arg(&path)
            .status()
            .expect("rustfmt");
        assert!(status.success(), "rustfmt failed");
        let formatted = fs::read_to_string(&path).expect("read temp");
        let _ = fs::remove_file(&path);
        formatted
    }

    #[test]
    fn raster_font_is_in_sync_with_committed_bdf() {
        let root = workspace_root();
        let bdf_path = root.join("raster/fonts/spleen-8x16.bdf");
        let out_path = root.join("raster/src/font/spleen_8x16.rs");
        let bdf = fs::read_to_string(&bdf_path).expect("read BDF");
        let generated = rustfmt_source(&generate(&bdf).expect("generate"));
        let committed = fs::read_to_string(&out_path).expect("read committed font rs");
        // A Windows checkout with core.autocrlf rewrites line endings only.
        assert_eq!(
            generated.replace("\r\n", "\n"),
            committed.replace("\r\n", "\n")
        );
    }
}
